# language: node_js
# node_js:
#   - "6"
#   - "7"
#   - "8"
# install:
#   - npm install
# scripts:
#   - npm run test
#   - npm run lint
# after_success:
#   - npm run coverall
# deploy:
#   provider: npm